### ISSUE TITLE
Frustrated

### ISSUE THREAD

**Issue by allenharguess701** [Montana-Media-Arts/441-WebTech-Spring2019#11]
I am very frustrated with github.

I am having lag times of upwards of 20 minutes where the pages are not updating with changes to the code. This makes it impossible to keep a good work flow. I push a change and it just simply will not update when I try to actually view the page. The file listed in the root will show the change but not the live file.

Also I am having an issue where i get undefined errors for variables when they are defined. 

My unfinished code is here

https://github.com/allenharguess701/Mart441/tree/master/HW-6

I cant even get the damn submit button to pass to the next page when I add in additional text boxes.

**Comment by michaelcassens** [comment]
Hi Allen,

I am so sorry to hear about your trouble.  That mist be really
frustrating.  You may have to jist work on it locally and then push your
changes when you are done.

Michael

**Comment by allenharguess701** [comment]
the problem is i keep getting undefined errors for variables that are defined. It's as if they are not being seen. I have to go to work in a bit so i cant finish this on time. I've been at this for six solid hours and it should not be even half this long to get such a simple program done. especially since you posted virtually the entire code as an example. yet even when I post that code it will not work.

**Comment by michaelcassens** [comment]
Hi Allen,

I actually made the due date for tomorrow night so that everyone would have
more time to work on this.  I am more than happy to take a look at your
code though.  I will take a look!

Michael

**Comment by allenharguess701** [comment]
thank. im really at a loss the passing of the info too the second page worked fine as long as I didn't add in the other text fields. once i did the button deactivates.

**Comment by MarkLannen** [comment]
Hi Allen

Apologies if this is not addressing your issue, but do you use a live server with your code editor? 

A live server with say, Atom or VS code, will show your updated changes immediately and you wouldn't have to wait for your github page to show the changes. 

I don't use Github as a way to preview changes, because it can be very slow (as you say) but just rely on it for version control.

If you wanted to try a live server I could point you in the right direction for set up!
