### ISSUE TITLE
image issue

### ISSUE THREAD

**Issue by kaitlinclifford** [Montana-Media-Arts/441-WebTech-Spring2019#2]
so one of the last things I have to do for hw1 is adding a background image.. but no matter what I do, I can't make a background image show up. 
Here's the important stuff from the index part (down below will be the CSS part).. if anybody knows what I'm doing wrong or wants me to try something please let me know because I'm stuck:/

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/31676610/51418081-a7e16680-1b3e-11e9-80b5-25b0131c10ad.png">

<img width="1444" alt="image" src="https://user-images.githubusercontent.com/31676610/51418068-95ffc380-1b3e-11e9-8e05-d4a88f41d3c6.png">

**Comment by jackelynstob** [comment]
because your image is in a folder your code should look like:
background-image: url("images/kaitlinimage.jpg");

also it looks as though your .JPG is capitalized in your folder, so if the lowercase doesn't work try that; sometimes it can be case sensitive.

**Comment by MarkLannen** [comment]
Hi Kaitlin

I think you need to reference the images folder in the path. Try: 

background-image: url("images/kaitlinimage.jpg")

Let me know if that works!

**Comment by MarkLannen** [comment]
Oh - and capitalize JPG in the css.

**Comment by kaitlinclifford** [comment]
ok.. I did what both of you said, but it still didn't work.. anything else i could try??:)

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/31676610/51418454-d06a6000-1b40-11e9-9e5f-50c006185d12.png">

**Comment by jackelynstob** [comment]
Will you post a screenshot of what your site looks like?

Is there any style showing up? Because it looks like you 
1) have 2 index.html's 
2) your style.css and index.html sheet are both in the "styles" folder. Which means when you link your style sheet in your html file, you don't need to address the styles folder. it could just say 

<link rel="stylesheet" type="text.css" href="style.css">; 

but I would recommend setting up the way you have your files different. 

your index.html file should be at the same level as you styles and images folder; as in your index.html should only be inside of the HW1 folder, and not inside of the styles folder, in which case you would need to address your styles folder in the code the way you have it.

**Comment by michaelcassens** [comment]
Hi Kaitlin,  

Would you mind posting a link to your repository?  You might try: background-image: url("../images/kaitlinimage.jpg");  The .. will tell it to go up a directory (out of the styles folder) and then go into the images folder to find your image. 

Hope this helps!

Michael

**Comment by MarkLannen** [comment]
OK - maybe it is because your style sheet is in a different folder from your your images.

Try background-image: url("..images/kaitlinimage.jpg")

**Comment by MarkLannen** [comment]
Ignore my suggestion - I left out the ../

I'm pretty sure Michael has it correct!

**Comment by jackelynstob** [comment]
ooo my code didn't appear on my comment! FaceTime me and we will figure it out.

**Comment by kaitlinclifford** [comment]
ok.. i got it figured out by adding the ../ infront of it like michael suggested... thanks guys for being willing to help!!!!

**Comment by MarkLannen** [comment]
Glad it is working!
